### ISSUE TITLE
Skin won't generate unless you edit the skin's name

### ISSUE THREAD

**Issue by Hiviexd** [clarks03/Osu-Instafade-Tool#1]
basically whenever I try to generate an instafade skin without changing any option, the program instacloses and the skin won't generate. only worked for me after I edited the name.
mayb worth investigating?

**Comment by clarks03** [comment]
I can't seem to replicate the issue... What skin were you trying to generate, and what did you change the name to so that it worked?

**Comment by Hiviexd** [comment]
`Karthy v5.6`, by default it renames it to `Karthy v5.6 - instafade` which doesn't want to work, it worked after removing the dash, so basically `Karthy v5.6 instafade`

**Comment by clarks03** [comment]
I have 3 potential things you could try doing:
1. Make sure the `Karthy v5.6 - instafade` directory doesn't already exist,
2. Ensure you downloaded the latest version of the tool (found [here](https://github.com/clarks03/Osu-Instafade-Tool/releases/tag/v1.0.0)),
3. Try pressing "Update" before saving the skin, to see if it just needs to refresh or something

Let me know if none of those work, I can make a push removing the dash from the auto-generated name.

**Comment by Hiviexd** [comment]
tried pressing update without changing anything, seems to work fine
